<?php

namespace AppBundle\Merchandise\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * ProductCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllSoldProductsGroupedByDivision($offset = null, $limit = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select(['d'])
            ->from('Merchandise:Division', 'd')
            ->where('SIZE(d.products) > 0')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()->getResult();

        return $result;
    }


    public function countFindAllSoldProductsGroupedByDivision($offset = null, $limit = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select(['COUNT(d)'])
            ->from('Merchandise:Division', 'd')
            ->where('SIZE(d.products) > 0')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()->getSingleScalarResult();

        return $result;
    }
}
