<?php

namespace AppBundle\Merchandise\Repository;

/**
 * LossLinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LossLinesRepository extends \Doctrine\ORM\EntityRepository
{
}
