<?php

namespace AppBundle\Merchandise\Repository;
use AppBundle\Merchandise\Entity\Restaurant;

/**
 * LossesSheetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LossSheetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTodayLossSheet($type, Restaurant $restaurant,$entryDate)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->from('Merchandise:LossSheet', 'ls')
            ->select('ls')
            ->where('ls.type = :type')
            ->setParameter('type', $type)
            ->andWhere('ls.entryDate = :today')
            ->andWhere('ls.originRestaurant = :restaurant')
            ->setParameter('today', $entryDate)
            ->setParameter('restaurant', $restaurant);
        $restult = $qb->getQuery()->setMaxResults(1)->getResult();
        if (count($restult) > 0) {
            $restult = $restult[0];
        } else {
            $restult = null;
        }

        return $restult;
    }

    public function findYesterdayLossSheet($restaurant, $type,$yesterday)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->from('Merchandise:LossSheet', 'ls')
            ->select('ls')
            ->where('ls.type = :type')
            ->setParameter('type', $type)
            ->andWhere('ls.entryDate = :yesterday')
            ->setParameter('yesterday',$yesterday)
            ->andWhere('ls.originRestaurant= :restaurant')
            ->setParameter('restaurant', $restaurant);
        $result = $qb->getQuery()->setMaxResults(1)->getResult();
        if (count($result) > 0) {
            $result = $result[0];
        } else {
            $result = null;
        }

        return $result;
    }
}
