<?php

namespace AppBundle\Merchandise\Repository;

/**
 * LossLineTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LossLineTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
