<?php

namespace AppBundle\Merchandise\Repository;

/**
 * NonTransformedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonTransformedProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
