<?php

namespace AppBundle\Merchandise\Repository;

/**
 * TransformedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformedProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
