 SELECT ticket.id,
    ticket.type,
    ticket.cancelled_flag,
    ticket.num,
    ticket.startdate,
    ticket.enddate,
    ticket.invoicenumber,
    ticket.status,
    ticket.totalht,
    ticket.totalttc,
    ticket.paid,
    ticket.operator,
    ticket.responsible,
    ticket.workstation,
    ticket.origin,
    ticket.destination,
    ticket.entity,
    ticket.customer,
    ticket.date,
    ticket.counted,
    ticket.operatorname,
    ticket.workstationname,
    ticket.originid,
    ticket.destinationid,
    ticket.cashbox_count_id,
    ticket_payment.num AS payment_num,
    ticket_payment.label,
    ticket_payment.amount,
    ticket_payment.type AS paiment_type,
    ticket_payment.operator AS payment_operator,
    ticket_payment.first_name,
    ticket_payment.last_name,
    ticket_payment.id AS ticket_payment_id,
    ticket_payment.id_payment AS payment_id,
    ticket_payment.code AS payment_code,
    ticket_payment.electronic
   FROM ticket,
    ticket_payment
  WHERE ticket.id = ticket_payment.ticket_id;