imports:
    - { resource: config_prod.yml }

swiftmailer:
    delivery_address:
        - mohamedali.zouai@talan.tn
        - annie.collignon@quick.be
        - barbara.geldof@quick.be
        - gol.oktay@quick.be
        - frank.perenzin@quick.be
        - philippe.sarre@quick.be
        - matthieu.poirier@quick.fr
        - abdelhak.belboul@quick.fr

parameters:
    router.request_context.scheme: http
    router.request_context.base_url: "http://197.3.0.226/quick.bo.recette.externe"
    wynd.url: "http://quickpprod.wynd.eu/api/orders/get_all/quick"
    wynd.api.user: "quick"
    wynd.api.secretKey: "2f6d70d20d23e782c8fc4637934090bda49eca80"
    asynch_postfix: ' > /dev/null &'
    ftp_host: "ftp.bidvest.be"
    ftp_user: "quickxmltest"
    ftp_pw: "@@Quick@6530@"
    ftp_port: 21
