<?php

namespace AppBundle\Security\Repository;

use AppBundle\Security\Entity\Role;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllButNotAdmin()
    {

        $queryBuilder = $this->createQueryBuilder('r');
        //        $queryBuilder
        //            ->where('r.label NOT IN (:superAdminRoles)')
        //            ->setParameter('superAdminRoles', Role::$SUPER_ADMINS_ROLES);
        $queryBuilder
            ->andWhere('r.label <> :roleEmployee')
            ->setParameter('roleEmployee', Role::ROLE_EMPLOYEE);
        $queryBuilder
            ->andWhere('r.label <> :roleAdmin')
            ->andWhere('r.label <> :roleSupervision')
            ->setParameter('roleAdmin', Role::ROLE_ADMIN)
            ->setParameter('roleSupervision', Role::ROLE_SUPERVISION);

        $result = $queryBuilder->getQuery()->getResult();

        return $result;
    }

    public function findAllButNotEmployee()
    {

        $queryBuilder = $this->createQueryBuilder('r');

        $queryBuilder->where('r.label <> :roleEmployee')
            ->setParameter('roleEmployee', Role::ROLE_EMPLOYEE);


        return $queryBuilder->getQuery()->getResult();
    }
}
